### ISSUE TITLE
MP4 support

### ISSUE THREAD

**Issue by iemejia** [saimn/sigal#106]
Hello,

I want first to thank you for your excellent gallery generator. I have been using it for more than one year and it is really good. I noticed than in recent versions you included support for videos, however I tried it and I saw that it converted the videos automatically to webm. I want to ask if you have any plans to support direct MP4 galleries, since mpeg4 is finally supported for most browsers.
http://caniuse.com/#feat=mpeg4

In addition most cameras already generate mp4 files, so it is simpler just to upload them if they are ok. I found bad to already lose more quality due to the reconversion to webm. However I understand if there are licensing arguments, but MP4 has more end support than webm in this moment too, and well the goal of this tool is to generate galleries for the end user.
http://caniuse.com/#feat=webm

Thanks,

ps. If you have plans to support this, I offer my help to beta test it :).

**Comment by muggenhor** [comment]
Isn't this addressed by #159 ?

Except maybe dual-encoding (both webm and mp4 with multiple sources in the `<video>` tag).

**Comment by saimn** [comment]
Yes, #159 is a first step, handling both webm and mp4 would be better but (as you may have noticed) I don't have a lot of time to work on sigal currently, so let's close this one and see later how to improve.
