### ISSUE TITLE
Sort albums by 'Date'

### ISSUE THREAD

**Issue by jrstarke** [saimn/sigal#121]
I really like this project, and I think there are only a few small things to get it to a point I love it.  

One of the things I'd like to be able to do is order my albums by reverse chronological (most recent at the top) so that when a user comes to my page, they see my most recent photos first. 

I can think of two ways of achieving this, but I'd like to get your thoughts. 

1. Add a `Date` property to the index.md file in the album, and add a configuration flag to sort by `date` to the config. When sorting the albums, if the `date` flag is set, order by this date, or alphabetic if none is available.
2. For each album, get the most recent exif from the medias, and then sort the albums based on their most recent media.

For complexity reasons, I'm more inclined to 1, but I figured it might be good to get some feedback before attempting to build something.

**Comment by saimn** [comment]
Fixed with #192
