### ISSUE TITLE
Escape special characters

### ISSUE THREAD

**Issue by shacker** [saimn/sigal#132]
I have 1500 album covers scanned into iPhoto, and many of them have "quotation marks" and # hash symbols in the titles. I batch export them to the Finder using "Title" for the filenames. sigal processes them just fine. But the resulting index.html has a lot of broken thumbnails, and if I try to right-click one to inspect, it crashes Chrome 39!. At first I thought it was the sheer volume of images but no - if I rename all those images without quotes or pound symbols and re-export, it's fine. Looking at the html source, it's because the quotation marks are landing inside quoted attributes such as alt tags and file names.

So sigal should escape or convert special symbols during export.

Thanks for this great tool!

**Comment by Lense** [comment]
This is still an issue. Simple reproduction:

![yewvl](https://user-images.githubusercontent.com/2699527/33866034-808bacee-dec2-11e7-9a9b-7946f9750344.png)

**Comment by saimn** [comment]
Should be fixed, see https://github.com/saimn/sigal/pull/278#issuecomment-428740043
Please reopen if you find another issue, thanks.
