### ISSUE TITLE
Py 3.4 support

### ISSUE THREAD

**Issue by michaelaye** [saimn/sigal#138]
Thanks for sigal!
What is needed for Python 3.4 support? Would love to see that happening!

**Comment by saimn** [comment]
Sigal is already compatible with python 3.
There is an encoding bug with non-ascii directory names, which is fixed on the git version, but otherwise it should be ok.

**Comment by saimn** [comment]
Assuming you had the same issue as #137, this is now fixed and release in version 0.9.2

**Comment by michaelaye** [comment]
Thanks, yes that was it!
