### ISSUE TITLE
Specify Author

### ISSUE THREAD

**Issue by misilot** [saimn/sigal#139]
Hi,

How would I go about placing a value into the variable Author as found here (https://github.com/saimn/sigal/blob/master/sigal/themes/colorbox/templates/media.html#L33)

As when I try adding author = "Name" to my sigal.conf.py it doesn't make a difference.

Thanks!

**Comment by saimn** [comment]
Hi,
It seems that this option was forgotten at some point ... :/
Thanks for the report, it will be foxed soon.

**Comment by misilot** [comment]
I think it needs to be changed to settings.variable
