### ISSUE TITLE
Support for GIF images

### ISSUE THREAD

**Issue by ludw** [saimn/sigal#140]
I have set up a gallery with sigal and would much appreciate if the .gif extension could be added to the list of formats recognized as an image. 

It seams the toolchain already works quite well with gifs, if I just rename the files to .jpg they will get thumbnails etc, but it complains about not being able to read exif data. 

Gifs can be quite useful for animated photobursts for example.

Thanks for a great gallery tool btw!

**Comment by saimn** [comment]
It should indeed be easy to add, I will try to look at this.

**Comment by mkell43** [comment]
Any updates on the possibility of this?

**Comment by Natim** [comment]
Oh I am also looking for that :+1:
