### ISSUE TITLE
shared hosting

### ISSUE THREAD

**Issue by wilfried18** [saimn/sigal#142]
It would be good to test, use this gallery to a shared hosting

**Comment by saimn** [comment]
Could you explain a bit ?

**Comment by wilfried18** [comment]
I would use on a shared server, but before installed on a server other quelquonc I would have liked to test your photo gallery to see eventual bugs, customization etc.
and after the installation section, it must be installed from the command line, so when shared servers this is not possible
can you make a version set by FTP

**Comment by saimn** [comment]
The aim of sigal is to generate the files and then send it to the server, so there is no need to install it on the server.

**Comment by wilfried18** [comment]
ok
