### ISSUE TITLE
Colorbox picture title handling

### ISSUE THREAD

**Issue by ThomasRgbg** [saimn/sigal#145]
Hi, 

in  sigal/sigal/themes/colorbox/templates/index.html the titles are above a colorbox defined:

```
 {% if 'sigal.plugins.media_page' in settings.plugins %}
<a href="{{ media.filename}}.html" class="gallery"
title="{{ media.title if media.title else media.filename }}"
data-href="{{ media.filename }}" {{ img_description(media) }}>
{% else %}
<a href="{{ media.filename }}" class="gallery" title="{{ media.filename }}" {{ img_description(media) }}>
{% endif %}
```
As far as I understand this code, the real title (as defined in the xxx.md) is only used if the media_page plugin is enabled. For me it looks like these are two independent things (having the title and creating the dedicated html files per picture).

By the way, how can I get the whole text of the title shown below the image and not above ? I know, thats a colorbox setting, not sigal, but maybe somebody knows the right config for this. 

Kind regards, 
Thomas

**Comment by saimn** [comment]
Hi, 
I think the title in the second case has not been updated, so `media.filename` should be replaced with `media.title if media.title else media.filename`.
For your second question, you can copy the theme somewhere, modify it (moving the title below the image should be enough) and tell sigal to use this theme.

**Comment by ThomasRgbg** [comment]
Ok, thanks. I changed this in my local code.
