### ISSUE TITLE
Export URL of updated pictures

### ISSUE THREAD

**Issue by ThomasRgbg** [saimn/sigal#158]
Hi, 

I have some wrapper around sigal, which sends a XMPP messages of updates in the gallery around. (Not very fancy, but I can upload it here, if somebody is interested)
For album names I can guess the URL, so I can embed this in the message.

However, the URLs of the pictures are dynamically numbered. 

So is there a way of using an absolute URL (hardlink) for a certain picture ? Or could I export out of Sigal the changed/added pictures ?

**Comment by saimn** [comment]
Hi,
> However, the URLs of the pictures are dynamically numbered. 
The url of the raw file is fixed (it uses the filename), but the url of the html page depend on the theme and on the javascript stuff.
> Or could I export out of Sigal the changed/added pictures ? 
No sorry, Sigal doesn't keep this information. Though it would be possible to store the list of files that have been processed (https://github.com/saimn/sigal/blob/master/sigal/gallery.py#L641), and make a plugin to use this information.

**Comment by ThomasRgbg** [comment]
Ok, good to know. But since I use the wrapper script to handle the pictures anyway, it was less work to create an other folder and link the files of the latest pictures in. But in case I find some time in future, I might have a look on a plugin again.
