### ISSUE TITLE
No index.html in the root

### ISSUE THREAD

**Issue by akaihola** [saimn/sigal#166]
I'm only getting `index.html` files in my `2014` and `2015` subdirectories, not in the root directory. As a result, I can't share a link to my whole photo gallery, but must share the `.../2014/` and `.../2015/` URLs separately.

**Comment by saimn** [comment]
Could you give more details on your configuration, and paste the full output of `sigal build -fd -n 1` ?

**Comment by akaihola** [comment]
Ok so it seems I had `['.*']` as my ignored directories in order to exclude `.git/` and `.venv/`, and this caused the above behavior. I changed that to listing those directories explicitly, and now everything works.

Note that due to the bottom-up `os.walk` order, I also had to include `.git/*` and `.venv/*` so directories embedded underneath those directories would not be processed.

**Comment by saimn** [comment]
Ah indeed, I see how this can be confusing, but I'm not sure if there is a way to improve this behaviour. Closing as the original issue is fixed.
