### ISSUE TITLE
Problem with .webm files

### ISSUE THREAD

**Issue by chrisisbd** [saimn/sigal#169]
I'm not sure if this is a bug or not but when I run 'sigal build' on my images it rejects any .webm files.

Even with --debug it doesn't seem to tell me anything useful, here is a section of the output (with the errors):-

...
...
...
DEBUG: Save resized image to /home/chris/sigal/_build/2012/09/11/dscf5146.jpg (JPEG)
DEBUG: Save resized image to /home/chris/sigal/_build/2012/09/11/dscf5147.jpg (JPEG)
DEBUG: Save thumnail image: /home/chris/sigal/_build/2012/09/11/thumbnails/dscf5146.jpg (JPEG)
DEBUG: Save thumnail image: /home/chris/sigal/_build/2012/09/11/thumbnails/dscf5147.jpg (JPEG)
DEBUG: Save resized image to /home/chris/sigal/_build/2012/09/11/dscf5148.jpg (JPEG)
DEBUG: Save thumnail image: /home/chris/sigal/_build/2012/09/11/thumbnails/dscf5148.jpg (JPEG)
ERROR: Some files have failed to be processed:
ERROR:   - 2010/09/29 - Dry fields at Newbourne/dscf443.webm
ERROR:   - 2012/06/05/mvi_0148.webm
ERROR:   - 2010/12/08/mvi_0029.webm
ERROR:   - 2013/12/08/dscf6470.webm
ERROR:   - 2014/07/07/mvi_0319.webm
ERROR:   - 2010/05 May/15/dscf3183.webm
ERROR:   - 2014/07/21/mvi_0320.webm
ERROR:   - 2014/07/21/mvi_0321.webm
ERROR:   - 2014/07/21/mvi_0322.webm
ERROR: You can run sigal in verbose (--verbose) or debug (--debug) mode to get more details.

INFO: Theme  : /usr/local/lib/python2.7/dist-packages/sigal/themes/galleria
INFO: Output album : <Album>(path=u'2014/04/08', title=u'08')
...
...
...

**Comment by saimn** [comment]
Are you sure you get no other info in the logs ? It seems there is an issue with the ffmpeg subprocess, and in debug mode stderr of this subprocess should be logged. Could you paste the full output ?

**Comment by chrisisbd** [comment]
Here's the result of running against a somewhat smaller subset which shows the errors:-

chris@esprimo$ sigal build -f --debug
INFO: Reading settings ...
DEBUG: Settings file: sigal.conf.py
DEBUG: Rewrite destination : _build -> /home/chris/sigal/_build
DEBUG: Settings:
{'albums_sort_reverse': False,
 'author': 'Chris Green',
 'autorotate_images': False,
 'colorbox_column_size': 4,
 'copy_exif_data': True,
 'destination': u'/home/chris/sigal/_build',
 'files_to_copy': (),
 'google_analytics': '',
 'ignore_directories': [],
 'ignore_files': [],
 'img_processor': 'ResizeToFit',
 'img_size': (800, 600),
 'index_in_url': False,
 'jpg_options': {'optimize': True, 'progressive': True, 'quality': 85},
 'keep_orig': False,
 'links': '',
 'locale': '',
 'make_thumbs': True,
 'medias_sort_attr': 'filename',
 'medias_sort_reverse': False,
 'orig_dir': 'original',
 'orig_link': False,
 'output_filename': 'index.html',
 'plugin_paths': [],
 'plugins': [],
 'source': u'/home/chris/tmp/pictest',
 'theme': 'galleria',
 'thumb_dir': 'thumbnails',
 'thumb_fit': True,
 'thumb_prefix': '',
 'thumb_size': (280, 210),
 'thumb_suffix': '',
 'title': u'Chris Green Pictures',
 'use_orig': False,
 'video_size': (480, 360),
 'webm_options': ['-crf', '10', '-b:v', '1.6M', '-qmin', '4', '-qmax', '63'],
 'write_html': True,
 'zip_gallery': False,
 'zip_media_format': 'resized'}
INFO:       Source : /home/chris/tmp/pictest
INFO:  Destination : /home/chris/sigal/_build
INFO:        Theme : galleria
DEBUG: Plugin paths: []
INFO: Using 4 cores
DEBUG: Albums:
[<Album>(path='.', title=u'pictest')]
INFO: Processing /home/chris/tmp/pictest/./img_0237.jpg
INFO: Processing /home/chris/tmp/pictest/./img_0238.jpg
DEBUG: Processor: ResizeToFit
DEBUG: Processor: ResizeToFit
DEBUG: Save resized image to /home/chris/sigal/_build/img_0237.jpg (JPEG)
DEBUG: Save resized image to /home/chris/sigal/_build/img_0238.jpg (JPEG)
DEBUG: Save thumnail image: /home/chris/sigal/_build/thumbnails/img_0238.jpg (JPEG)
DEBUG: Save thumnail image: /home/chris/sigal/_build/thumbnails/img_0237.jpg (JPEG)
ERROR: Some files have failed to be processed:
ERROR:   - ./mvi_0320.webm
ERROR:   - ./mvi_0322.webm
ERROR:   - ./mvi_0321.webm
ERROR: You can run sigal in verbose (--verbose) or debug (--debug) mode to get more details.

INFO: Theme  : /usr/local/lib/python2.7/dist-packages/sigal/themes/galleria
INFO: Output album : <Album>(path='.', title=u'pictest')
Done.
Processed 2 images and 3 videos (3 failed) in 0.47 seconds.
chris@esprimo$

**Comment by wendrowycz** [comment]
On Ubuntu, helped install ffmpeg with the --enable-libvpx.

**Comment by bluesponge** [comment]
on lubuntu 15.04, installing ffmpeg, libvpx1, libvpx-dev and vpx-tools has solved «ERROR: Some files have failed to be processed». unfortunately, on lubuntu 14.04 (LTS) the problem persists after installing libvpx1, libvpx-dev and vpx-tools. ffmpeg is not in the official repositories in 14.04. any suggestions ?

**Comment by bschousek** [comment]
Instructions at http://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/ appear to be working for me using Unbuntu 14.04 LTS

**Comment by saimn** [comment]
Sigal should now give a better idea of the issue in debug mode (and stop the processing). So to debug issues with videos / ffmpeg, one should use `sigal build -d -n 1`
Closing this issue since it was opened a long time ago.
