### ISSUE TITLE
Fullscreen Icon for Galleria theme

### ISSUE THREAD

**Issue by ThomasRgbg** [saimn/sigal#170]
I have two suggestions for a tiny improvement of the fullscreen icon.

In https://github.com/saimn/sigal/commit/26a28ba070b98d752d8c9952b22a1f2ebe684b72 is a little bug. The fullscreen Icon is within the {% if settings.show_map and album.show_map %} condition, so will be only shown when the map is enabled. 

And the current icon is pretty large, how about putting it below or above the "i" icon which opens the info box ?

**Comment by saimn** [comment]
Yes, you're totally right, it would be nice to improve this with smaller and better integrated icons, and put the icon for everybody.

**Comment by saimn** [comment]
Done with https://github.com/saimn/sigal/commit/32459d74e6a588bca7f0cf690c8737c9770906fd
