### ISSUE TITLE
output more exif on template

### ISSUE THREAD

**Issue by fghhfg** [saimn/sigal#174]
now we can output part of [exif on template](https://sigal.readthedocs.org/en/latest/themes.html#simpler-exif-data-output).

can we output title and comment of exif tag?

<img width="903" alt="capture" src="https://cloud.githubusercontent.com/assets/1284845/10365946/95e3eca0-6df9-11e5-93d2-be313d83db5c.PNG">

then I can write data on image's exif on windows explorer...

**Comment by saimn** [comment]
All the EXIF tags are available in `media.raw_exif`.
`media.exif` contains a cleaned version of several for easier use, and it is possible to add more if there is a need for this.
Does that answer your question ?

**Comment by fghhfg** [comment]
```
./gallery.py:158:        return (get_exif_tags(self.raw_exif)

./image.py:201:def get_exif_tags(data):
```
