### ISSUE TITLE
How to output no-english string exif?

### ISSUE THREAD

**Issue by fghhfg** [saimn/sigal#175]
no-english string exif in [get_exif_tags](https://github.com/saimn/sigal/blob/master/sigal/image.py#L201) is something like this one:
```
{'Artist': 'authorrr', 59932: (b'\x1c\xea\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\
```

Try to output no-english string exif in [get_exif_tags](https://github.com/saimn/sigal/blob/master/sigal/image.py#L201):

```py
 print (data['ImageDescription'].decode('utf8') if compat.PY2 else 'no')
```

It doesn't work. I always get `no`.

How do I handle this part `b'\x1c\xea\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\`?

**Comment by saimn** [comment]
It seems to be some binary data, but I don't find much information about this 59932 tag.

**Comment by fghhfg** [comment]
this two line is from [get_exif_data](https://github.com/saimn/sigal/blob/master/sigal/image.py#L179)
```py
    exif = img._getexif() or {}
    data = {TAGS.get(tag, tag): value for tag, value in exif.items()}
```

and

`exif line` is a lot (key & value), key is some number, value is content we need.
`data line` convert `key` in `exif line` to something like `ExifOffset`, `ImageDescription'`... 
and some key still remain number.

Actually I want to ask how do I convert binary data to real text?

**Comment by fghhfg** [comment]
ran [imagemagick](http://www.imagemagick.org/) in windows, it has very similar issue... =.= :persevere:

**Comment by fghhfg** [comment]
OK, exif text fields are not stored using UTF and most of the time there is no indication of the character set encoding.

That's why!
