### ISSUE TITLE
Videos on Iphone/Ipad

### ISSUE THREAD

**Issue by ThomasRgbg** [saimn/sigal#196]
Hi, 

in the config it is possible to encode videos as mp4 instead of webm. This would allow to see this videos also on Safari-devices. However, there some issues: (using the galleria theme)

- Obviously, the mime-type is always: type='video/webm'

- But the html tags cause also some problems. What I found on the Internet, the html should look like here: http://www.justinwhall.com/html5-video-playing-ios-devices 
I tried to play around with the index.html a bit, but I think the theme makes it more complicated...

**Comment by saimn** [comment]
For the galleria theme the mime type is hard-coded, this is easy to fix:
https://github.com/saimn/sigal/blob/master/sigal/themes/colorbox/templates/index.html#L87
https://github.com/saimn/sigal/blob/master/sigal/themes/galleria/templates/index.html#L150
But I don't understand your second point, the HTML in your link is similar to the one used in the templates, so ?

**Comment by ThomasRgbg** [comment]
What I mean is, it seems the Safari browser expects a syntax like:

`<video controls>
	<source src="movie.mp4" type='video/mp4'>
</video>`

But in https://github.com/saimn/sigal/blob/master/sigal/themes/galleria/templates/index.html#L147 - 149 is also the filename referenced and this might confuse the browser ? 

At least only changing the mime type don't fix the issue. But after trying around, one time the video was played, when I was heavily scrolling between the pictures/videos. I'm not an expert, but I guess it might be related with the additional file references ?

**Comment by saimn** [comment]
I fixed the mime-type, but I don't understand the filename issue: `<source src='{{ media.filename }}' ...` will generate the same line as the one from your example, there is no "additional file references".

**Comment by ThomasRgbg** [comment]
The <video.....> sequence is within the data-layer tag. I think Safari has difficulties to interpret this.

**Comment by saimn** [comment]
> The sequence is within the data-layer tag

Sorry but I don't understand ?

**Comment by saimn** [comment]
Just released version 1.1.0, please check and reopen if the issue is still there.

**Comment by ThomasRgbg** [comment]
Works, thanks a lot!
