### ISSUE TITLE
Photoswipe - Video not displayed, ok with galleria

### ISSUE THREAD

**Issue by bmsleight** [saimn/sigal#197]
```
$ sigal --version
sigal, version 1.0.1
```

With photoswipe
http://imgur.com/a/aWELF

```
$ diff sigal.conf.py_photoswipe sigal.conf.py
26c26
< theme = 'photoswipe'
---
> theme = 'galleria'
```

With galleria
http://imgur.com/a/vch0e

Sigal is Brilliant.
Thanks,
Brendan

**Comment by saimn** [comment]
Unfortunately photoswipe does not support videos (as mentioned [here]( http://sigal.saimon.org/en/latest/themes.html)). See also https://github.com/dimsemenov/PhotoSwipe/issues/651
Thanks for the kind words :)
