### ISSUE TITLE
.webm videos not opening correctly

### ISSUE THREAD

**Issue by tmelin** [saimn/sigal#201]
I'm not sure is this a browser issue or a Sigal issue, but reporting here to perhaps gain understanding.

sigal version: 1.0.1
theme: colorbox

Playing of video files does not work as one would expect.
The issue is as follows; Starting from the main view of the album. When clicking on a video-file thumbnail, it first opens the view that shows one file at a time. I see the play button etc, but at soon as the play button is pressed, it returns to the main overview of the album instead of playing the video file. I.e it works as if the video was a normal picture and returns to the main view.

I get the video playing by selecting "view video" from Firefox popup menu, but that is not the behaviour I want or would expect.

Tested with Firefox 45.0.2 on a Mac, Safari also behaves the same.  Is this some issue with my config just a known feature?

**Comment by saimn** [comment]
I don't know what to propose to help you here ... maybe try with mp4 instead ? It has a wider support than webm, so it may be a better alternative anyway.

**Comment by tmelin** [comment]
.webm videos play fine, the problem is that when you click on a video to play it - the browser jumps back to the album view. To me, this looks like a problem in the theme.

For normal pictures, clicking on the picture to go back to the gallery view (four colums thumbnail) is fine, but for videos, one would expect the video to start playing, and not just close the single view window.

**Comment by saimn** [comment]
Ok, so there are a few things you could try:
- For Sigal 1.1 I have updated colorbox's javascript library, so maybe this issue was fixed ?
- Did you try with the galleria theme, to check if it is caused by the theme ?
- You could also check the browser console to see if there is an error message.

**Comment by tmelin** [comment]
Updated to sigal 1.1, did not have an impact on this issue.
Also tried galleria theme, it is indeed a colorbox theme problem. With the galleria theme it works.

I'm pretty sure its a html problem.
There should be something blocking a video from closing when pressing play, instead of closing the video as happens when you press a normal jpg image. I.e. video format files need separate handling written into the static html generated code.

**Comment by saimn** [comment]
Oh, found the issue ! The touchswipe plugin added in #116 was always closing the colorbox window, which of course is wrong for videos. I should have noticed this before, sorry.

**Comment by tmelin** [comment]
Nice! I'm not building from sources so I'll wait for 1.2.0 to come out to test it myself.

Thanks,
Tomas

**Comment by saimn** [comment]
1.2.0 is already available ;-), I published it yesterday.
