### ISSUE TITLE
zipfile.LargeZipFile: Zipfile size would require ZIP64 extensions

### ISSUE THREAD

**Issue by TuxDream** [saimn/sigal#204]
To support large zip file, edit /usr/lib64/python2.7/site-packages/sigal/gallery.py

`if zip_gallery and len(self) > 0:
            archive_path = join(self.dst_path, zip_gallery)
            archive = zipfile.ZipFile(archive_path, mode='w',**allowZip64=True**)`

**Comment by saimn** [comment]
Good suggestion, thanks. (Also it is the default since Python 3.4).

**Comment by Ritesh-Sharma** [comment]
@TuxDream : I got this error while deploying my artifacts to remote nodes through Ansible , as a solution i tried to edit gallery.py as mentioned by you but i am unable to find sigal directory in site-packages (in python 2.7 ); is anything wrong with my python installation ? or do i need to explicitly create the sigal/gallery.py and fill the logic for **allowZip64=True** in it.
