### ISSUE TITLE
Mapquest tiles no longer available without API key

### ISSUE THREAD

**Issue by ehcloninger** [saimn/sigal#218]
I enable maps on my theme (show_map = True), which activates MapQuest tiles (pin in upper right of image). In the themes, this is written in themes/*/templates/index.html during function init_maps(). As of 2016/07/11 the Mapquest tile server is no longer available for open public use without an API key. 

According to their announcement, an API key can have 15,000 accesses per month. I imagine you want to set the templates up to require the user to get their own API key or else link to someone else's map tiles.

http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

![screen shot 2016-09-06 at 4 23 04 pm](https://cloud.githubusercontent.com/assets/398033/18292529/46720f74-7453-11e6-81ba-16ce13813297.png)

**Comment by saimn** [comment]
Thanks for reporting this. What are the alternatives ?

**Comment by saimn** [comment]
So, first option, the Mapquest plugin for Leaflet, which requires a key:
https://developer.mapquest.com/documentation/leaflet-plugins/maps/

**Comment by 153957** [comment]
There are many alternative tile server providers, pick one (without an api key) you like:
https://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by saimn** [comment]
Thanks @153957 , let's use leaflet-providers to give users the choice.
