### ISSUE TITLE
Personalized ip server

### ISSUE THREAD

**Issue by Clarin98** [saimn/sigal#219]
Hi, thanks for this great software.

I want to execute my sigal server on a different IP (like 192.168.0.xx:8000, nor localhost) but I can't see how to do this, can you help me? Thanks :)

**Comment by saimn** [comment]
It would be to add a command-line argument, but what would be the use case for this ?

**Comment by Clarin98** [comment]
For an unknown reason when I launched anything in a localhost (127...) I can't see it in a public IP (even with port forwarding and all the correct procedure), so I launch the apps in address like 192... and it will works public. However, I don't need this feature now, thanks for your help :)
