### ISSUE TITLE
Folders with non- ascii characters in "ignore_directories" are not ignored

### ISSUE THREAD

**Issue by cbast** [saimn/sigal#222]
When trying to filter out some folder in sigal.conf.py, if a folder contains non-ascii characters, the folder is not ignored.

e.g.
I have three folder: filtré, filtered and unfiltered. I want to only keep "unfiltered" in the output, so I write the following:
`ignore_directories = [ "filtré", "filtered" ]`

The build succeeds, but in the output folder, I get folders filtré and unfiltered.  Here the [debug output](http://pastebin.com/yV02jRdm)

I also tried to replace the "é" letter with the "?" character (to match any character) and it happens to work as expected in these simple test folders, but the build actually fails on my "real" folder with the following [error](http://pastebin.com/01Ajr24y)

**Comment by saimn** [comment]
I have tested and it works. I think it doesn't work in your case because you are using `"filtré"` instead of `u"filtré"`: when using special characters, you need to use an unicode string. Or use python 3 ;-)

**Comment by cbast** [comment]
Yes that was the problem. Thanks.
