### ISSUE TITLE
add support for 3gp

### ISSUE THREAD

**Issue by pmlopes** [saimn/sigal#226]
This is a video format common on some Android devices and supported by ffmpeg so I guess it could be easily added to sigal.

**Comment by saimn** [comment]
Do you mean in input or output ? 
As an output format, I don't think 3gp is supported by the `<video>` tag.
As input, every format that is supported by ffmpeg should already be supported, and will be converted to webm or mp4.

**Comment by pmlopes** [comment]
Sorry for the confusion, I mean input only. The fix is easy as add the extension to two places.

**Comment by saimn** [comment]
Ah yes indeed, it should be added to the list of extensions.

**Comment by saimn** [comment]
@pmlopes - Done, if you want to test.

**Comment by pmlopes** [comment]
Works :+1:
