### ISSUE TITLE
Recreate index.html

### ISSUE THREAD

**Issue by cedricpim** [saimn/sigal#232]
Great software, easy to use and install, thanks.

I just come up with a problem that I thought might warrant an additional `sigal build` option.

Let's say that I have used build with a bunch of directories and, now, I use it in a new directory. The main index.html file get recreated only with the new directory that was processed, so through the website, I only have access to the new photos but the other ones are still under `_build`.

What I end up doing was to copy `_build` as `_build_backup` and use `_build_backup` as the source and `_build` as the destination but I think it can be interesting for sigal to allow the recreation of the main index.html.

**Comment by saimn** [comment]
Thanks :)
This is not intended to work that way: you have to keep the source directory, which was used to generate your first `_build` directory. You can add new directories in the source one, and Sigal will check and build only the new images. But, mostly for performance reasons, it will not check and remove from the build directory the images that have been removed in the source one. So it is not possible to parse the build directory to update the index file, the idea is that the build directory should reflect what is in the source one.

**Comment by cedricpim** [comment]
I came up with this suggestion because I was keeping the pictures I wanted on the source directory but as it grew, and I didn't have more disk space, I had to remove the older ones (but wanted the sigal gallery to still display them).

**Comment by saimn** [comment]
I understand your use case but as I said it is not possible to rely on what's in the build directory. The idea is that this directory can be deleted at any moment and recreated from scratch, which also simplifies the backups etc. So sorry, but I will close the issue as it will never be fixed :/

**Comment by cedricpim** [comment]
Sure thing. Thanks for the reply :+1:
