### ISSUE TITLE
video is half-size in galleria theme

### ISSUE THREAD

**Issue by alexbozhenko** [saimn/sigal#250]
Hello. I'm using sigal for sharing photos with my family and it's great.
I noticed that in galleria theme video is not showing in full size. My video params are:
```
grep video_ sigal.conf.py 
video_format = 'mp4'
video_size = (720, 540)
```
![video_not_full_size](https://cloud.githubusercontent.com/assets/5295986/26560138/0676c96e-4469-11e7-8c4f-cdf552a65820.png)
![video_not_full_size2](https://cloud.githubusercontent.com/assets/5295986/26560173/4fbd6d58-4469-11e7-9627-1d1cc997b510.png)

On the screenshots you can see that video(520px) is about half-size galleria-image div(960px). I tried to dig into javascript, but was not able to find a place in the code where resize happens. Is it a galleria js problem?

**Comment by saimn** [comment]
i think galleria computes the maximum area that is needed for all the images/videos, to avoid having to resize this display area when you go to the next/previous item. So I guess you other images are wider or taller ?

**Comment by alexbozhenko** [comment]
All the videos are the same 720*540, but all the images are wider and taller. Other images fit exactly to the black rectangle. So should I ask them about it?

**Comment by saimn** [comment]
Yes, as it seems to be the normal behavior of galleria. You could also look at their docs, there is maybe a way to set the size in JavaScript. But then, what behavior do you expect, should the images be resized to fit this size ?

**Comment by saimn** [comment]
Closing as imo it is due to galleria. Please reopen if you think something can be done in sigal.
