### ISSUE TITLE
Ability to force thumbnail for album

### ISSUE THREAD

**Issue by no-boot-device** [saimn/sigal#254]
I want to have any file named `folder.jpg` in my folders be set to the thumbnail, but as far as I can see there's no good way to do this. Using photoswipe theme.

**Comment by saimn** [comment]
It's possible with a file inside each album to specify its thumbnail: http://sigal.saimon.org/en/latest/album_information.html
If you have many albums and really want to force this, it should not be hard to write a little plugin.

**Comment by saimn** [comment]
Closing as I think it already exists, please reopen if needed.
