### ISSUE TITLE
No handlers could be found for logger "sigal.image"

### ISSUE THREAD

**Issue by bernardcwj** [saimn/sigal#259]
Due to the size of my images being very small, when i clicked on the image in colorbox theme, the images are blocked by the controls. And when i set img_processor = 'None' in sigal.config.py, i encountered the following error:
No handlers could be found for logger "sigal.image"

Any help is appreciated!

**Comment by saimn** [comment]
Not sure about the logger error, I think it's harmless but it should happen. Do you a more detailed message or traceback ?
Or maybe, did you use `img_processor = 'None'` or `img_processor = None` ? You have to use to second. 
Also if you set a desired size (`img_size`) larger than the size of your image, they should not be modified.

**Comment by saimn** [comment]
Closing, please reopen if you have more information.
