### ISSUE TITLE
Sigal does not urlencode filenames

### ISSUE THREAD

**Issue by larsks** [saimn/sigal#262]
Sigal does not urlencode filenames.  So if you have a file named `img-09:10:10.jpg`, Sigal will happily generate:

    <img src="img-09:10:10.jpg">

And of course this looks like a URL that uses the `img-0:` schema, so the browser says:

    ERR_UNKNOWN_URL_SCHEME

**Comment by Ferada** [comment]
Had a quick try on that with that and whitespace as well, I suspect it might be as simple as https://github.com/Ferada/sigal/commit/04303c5cd0da4a24bf7f3b0bf2df660112bb78a8 - @larsks if you use that branch, https://github.com/Ferada/sigal/tree/fix-filename-quoting, is it fixed for you?

**Comment by 3onyc** [comment]
I've been poking around in this but and the urls for the media are easy enough, but we're treating the album thumbnails as both path & url, so it's a bit of a tricky one as to where to encode those.

**Comment by larsks** [comment]
@Ferada I missed your comment earlier; I'll try taking a look today. Based on @saimn's comment, though, I suspect I'll still have a problem because I have directories as well as files that contain `:`.

**Comment by saimn** [comment]
So I indeed have a branch with a start of something to address this issue: (and I also another branch locally with a different fix 😮 ): https://github.com/saimn/sigal/commit/bb5a9500f0a04b50ac5ccc14354bd8ce2e744177
Not sure what's the status with this branch, I don't remember.

And I don't know if/when I will be able to look more in detail into this, so someone wants to it's welcome. The idea would be to use a new `.url` property both for files and for albums (I should have done that from the beginning...).

**Comment by saimn** [comment]
Fixed by #345
