### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by saimn** [saimn/sigal#265]
Once v1.4 is released (which I would like to do in a near-future), I think it will be about time to drop Python 2 support. And take advantage of Python 3 new features 😄

**Comment by anarcat** [comment]
i definitely encourage you to do that. doing py2 + py3 is a pain, so much new good stuff on py3's side, even though performance is not quite there yet. py2 will be EOL soon (2020!) anyways.

**Comment by hugovk** [comment]
Here's some projects which are dropping Python 2 before 2020:
* http://www.python3statement.org/#sections40-timeline
* https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

**Comment by saimn** [comment]
See #309.
