### ISSUE TITLE
PIP package broken

### ISSUE THREAD

**Issue by nsukur** [saimn/sigal#266]
When installing with PIP on Ubuntu 17.04 (Python 3.6) `sigal` doesn't end up on the `$PATH`.

When using `easy_install` everything works.

Thanks!

**Comment by saimn** [comment]
How are you installing, with `sudo`, or `--user` ? This determines the path, then this path must be in your `$PATH` which may not be the case by default.

**Comment by anarcat** [comment]
i just tried a `pip3 install sigal` on debian stable and it works fine.

**Comment by saimn** [comment]
Closing as it looks like an issue on your side, please reopen with more details if needed.
