### ISSUE TITLE
Formatting media.datetime

### ISSUE THREAD

**Issue by nelsonov** [saimn/sigal#271]
In the documentation for themes, you mention formatting datetime like this:
`{% if media.exif.datetime %}`
`    {{ media.exif.datetime.strftime('%A, %d. %B %Y') }}`
`{% endif %}`

However, media.exif.datetime does not appear to be a Python datetime object.  When I attempt this in the colorbox index.html, I get the following error
`File "/media/cams/themes/colorbox/templates/index.html", line 44, in template`
`    data-date=", {{ media.exif.datetime.strftime('%c') }}"`
`jinja2.exceptions.UndefinedError: 'unicode object' has no attribute 'strftime'`

Am I missing something?

Thank you.

**Comment by saimn** [comment]
The documentation is wrong (sorry!), `datetime` is indeed a formatted string (with `strftime('%A, %d. %B %Y')`), but there is also a `dateobj` key with the Python datetime object:
https://github.com/saimn/sigal/blob/master/sigal/image.py#L303-L316
Can you check if it works for you ? (And if you want to fix it, you're welcome :wink: )
