### ISSUE TITLE
Broad Exceptions and Error Logging

### ISSUE THREAD

**Issue by dumrauf** [saimn/sigal#286]
Running `sigal build` suddenly started producing error messages like
```
2017-11-27 01:08:40,696 - sigal.gallery - WARNING - Could not read EXIF data from /whats/going/on/here/some.jpg
```
After a lengthier investigation and extending
https://github.com/saimn/sigal/blob/e35d95557a31b39e5d497808574920cf305a221e/sigal/gallery.py#L174
it turned out that the issue was actually
```
IOError: [Errno 13] Permission denied: u'/whats/going/on/here/some.jpg'
```

Would it be possible to log the error message of the exception alongside the `Could not read EXIF data from %s` message? I could image this to avoid false positives and speed up other people's debugging as well in case they've got environment issues.

Thanks for the great work you've done so far, chaps!

**Comment by saimn** [comment]
Good idea, thanks for the report. I have done this in the commit above, could you check with the dev version of it works for you ? (I don't have images failing here on the current laptop :/ )

**Comment by dumrauf** [comment]
Thanks for adding the error logging - much appreciated!

I can confirm that for my scenario of knackered permissions of an image, `sigal build --verbose` came back with 
```
...
Processing /whats/going/on/here/some.jpg
Failed to process: IOError(13, 'Permission denied')
...
```
All pictures that had the correct permissions were processed. Well done!

On a different note, I've noticed that `sigal build --debug` behaves slightly different.  It stops the execution after throwing the exception
```
...
IOError: [Errno 13] Permission denied: u'/whats/going/on/here/some.jpg'
```
All remaining pictures do not seem to get processed. I'm not up to speed on the features of the latest releases, maybe this is expected and what people actually want.

Keep up the good work!

**Comment by saimn** [comment]
Yes, for `--debug` it is the expected behavior, the idea is to help to identify issues. Thanks for the feedback!

**Comment by dumrauf** [comment]
Thanks for clarifying. Your responsiveness and quick turn around time are massively appreciated!
