### ISSUE TITLE
transparent info box?

### ISSUE THREAD

**Issue by anarcat** [saimn/sigal#308]
what would be the best way to make the background color on the galleria infobox transparent?

I'd like to turn this:

![image](https://user-images.githubusercontent.com/796623/37046958-933598b6-2137-11e8-8580-7c553214fe26.png)

into that:

![image](https://user-images.githubusercontent.com/796623/37046978-a722b692-2137-11e8-96d4-53b169e6dc92.png)

I did this by changing the `background-color` on the `galleria-info-text` element to `rgb(0,0,0,0.5)` (instead of `#000`) but I am not sure I want to hack at the galleria theme directly...

**Comment by saimn** [comment]
Not sure if this should be changed on the default style as it could be less readable on more white images ?
And currently there is no way to customize easily a theme, other than using a modified copy. But that would certainly be a useful feature, we could have a `user_css` setting to point to a file that would be loaded on each theme, to allow easy customization like this that can be done in pure css.

**Comment by anarcat** [comment]
well, it's "black with transparent background", so presumably it would still work white dimmer images... 

a `user_css` would certainly be useful, and yeah, maybe i just need to take this upstream to galleria, shouldn't i? :)

**Comment by saimn** [comment]
> well, it's "black with transparent background", so presumably it would still work white dimmer images...

yes, maybe, but it's something t check. If it gives good results, I'm fine with integrating this change in the default style (in sigal).

> a user_css would certainly be useful, and yeah, maybe i just need to take this upstream to galleria, shouldn't i? :)

It would be useful for all themes in sigal, so that's really something to do on our side I think.

**Comment by anarcat** [comment]
okay then, here's how it looks like with a (mostly) white background:

![image](https://user-images.githubusercontent.com/796623/37064734-2c87edfa-216c-11e8-8597-c1ec64d24a76.png)

LGTM. :)

**Comment by saimn** [comment]
The contrast seems too poor to me (see below), it could work with alpha 0.8 but is it enough transparent for you ?

![capture d ecran de 2018-03-07 00-39-02](https://user-images.githubusercontent.com/311639/37065192-2721f156-21a0-11e8-8143-78e7dda2f8e3.png)

With 0.8:
![capture d ecran de 2018-03-07 00-44-14](https://user-images.githubusercontent.com/311639/37065341-b831557e-21a0-11e8-85ba-9878f46eeceb.png)

**Comment by anarcat** [comment]
sure, as long as there's some transparency...

(wow, that's a *fast* shot!!! one billionth of a second?? that can't be right...)

**Comment by saimn** [comment]
Ok, after some testing I think 0.7 works well so I added this, thanks for the suggestion.
