### ISSUE TITLE
Integrating a dynamic backend

### ISSUE THREAD

**Issue by Glandos** [saimn/sigal#319]
I've already worked on a flask-based application to be able to quickly write titles and descriptions to my photos:
![sigal_admin](https://user-images.githubusercontent.com/297578/37735958-dc60ae12-2d4f-11e8-946c-636cdb873fc0.png)

This application is writing markdown files, ready to be read by `sigal` upon building. It is currently an external application, with a very raw UI (as you can see…). Another goal I'd like to reach with it is the ability to select media in order to produce filters for `sigal`.

But before going on this, I'm wondering if it would be interesting to integrate this in `sigal` itself, or to keep it separate.

For those interested, the code is currently on https://framagit.org/Glandos/sigal-admin.

**Comment by saimn** [comment]
Nice weekend hack ;), it could be useful indeed. I have no strong feelings about the integrate or separate question, there are pros and cons for both, but I guess that separate would be easier as the app may have its own development pace, and also I cannot commit on more maintenance work. However we need to find a way to make these community projects more visible, I was thinking about using the Github wiki for this, or is it better in the docs ?

**Comment by saimn** [comment]
Let's try with this: https://github.com/saimn/sigal/wiki

**Comment by Glandos** [comment]
OK, let's start this way. I've written a readme with some basic instruction to try to attract some people.
