### ISSUE TITLE
video is not playable with galleria theme

### ISSUE THREAD

**Issue by evgmik** [saimn/sigal#321]
Looks like update to newer galleria version broke video playback.

How to check:
replace theme='colorbox' => theme='galleria' in the config stored in 'tests/sample/sigal.conf.py'
run 'make demo' point browser to video testing link. The video is not playable anymore.

I did not do the proper bisect but everything was fine with git version dated by  about 2017-12-17

**Comment by saimn** [comment]
It works with the 1.4 release, so probably related to #312  (cc @edwinsteele - if you have any idea?).
Thanks for the report, it seems that we missed that !

**Comment by saimn** [comment]
See #322 for a possible fix.
