### ISSUE TITLE
Symlinks in chroot

### ISSUE THREAD

**Issue by telefax** [saimn/sigal#333]
Would it be possible to have a configuration option where you specify the symlink root?

my httpd daemon runs chrooted and the symlinks contains the full path (which the chroot doesn't know anything about).

Thanks!

**Comment by telefax** [comment]
So, instead of linking to /mnt/some_mountpoint/www/images/ it would link relative to the chroot, such as /www/images/ or so.

**Comment by saimn** [comment]
I understand that this behavior can be annoying, but I'm a bit reluctant to add such a specific option ... Another solution is to deactivate symlink, if your gallery is not too big the cost is small enough.

**Comment by klnavajo** [comment]
I have the same problem when using the option `use_orig = True`.  Links are not relatives (but absolute path), so, images and site directories are not portable.

Perhaps a solution (`utils.py`) :

```
def copy(src, dst, symlink=False):
    """Copy or symlink the file."""
    func = os.symlink if symlink else shutil.copy2
    if symlink and os.path.lexists(dst):
        os.remove(dst)
    if symlink:  # relative symlink from dst
        func(os.path.relpath(src, os.path.dirname(dst)), dst)
    else:
        func(src, dst)
```

**Comment by saimn** [comment]
> Links are not relatives (but absolute path), so, images and site directories are not portable.

Yes, but I guess that relative paths would not be so practical in many cases, as you would need to keep the same directory structure or copy the src directory with the destination one. Maybe a solution could be an option to use hardlinks, to save space on the computer building the gallery but keeping a destination directory that can be easily moved or copied ?

**Comment by klnavajo** [comment]
Hi, the solution of an option and hardlink, that sounds good :)

**Comment by klnavajo** [comment]
Hi, the solution of an option and hardlink, that sounds good :)
