### ISSUE TITLE
Tests are not included in pypi source tarball

### ISSUE THREAD

**Issue by dvzrv** [saimn/sigal#337]
Hi!
I'm about to move sigal to Arch Linux [community].
I noticed, that the pypi source tarball is lacking the tests though. Could you add them? Pypi is our default upstream. Thanks!

**Comment by saimn** [comment]
Hi,

> I'm about to move sigal to Arch Linux [community].

Good news, thanks!

> I noticed, that the pypi source tarball is lacking the tests though. Could you add them? Pypi is our default upstream.

There is a PR related to this (#323), but as explained there, I have to check the test images to be sure that their license is compatible with MIT. Most images are mine, but some were added in PRs, and I'm not sure that everything is free :/ so I really need to verify this.

**Comment by saimn** [comment]
Fixed by #340 and #323, so it will be in the next release.

**Comment by saimn** [comment]
@dvzrv - Btw, I had a look at the new package, and there a few dependencies that are not needed or could be optional:
- twine is not needed, it is only useful to upload a package to PyPI but nothing specific to sigal.
- feedgenerator is optional, for the feeds plugin
- there are also Brotli and zopfli which are optional, for the compress assets plugin

I updated the documentation with these information: http://sigal.saimon.org/en/latest/installation.html#dependencies

**Comment by dvzrv** [comment]
@saimn thanks for the update! Will change the packages asap! :)

**Comment by dvzrv** [comment]
Hmm, the tests are not included in the 1.4.1 tarball on pypi though.
