### ISSUE TITLE
test_album fails on fr_FR.UTF-8 unavailability

### ISSUE THREAD

**Issue by dvzrv** [saimn/sigal#338]
During packaging for Arch Linux [community], I've stumbled over the failing tests in `test_album` (see attachment).

In the clean chrooted build environment the `fr_FR.UTF-8` locale is not available by default.
Is that locale specifically required for the tests? Is there no way of mocking this, so that any available UTF-8 locale can be used there?

I have to disable these tests for now, because they break the build (and reproducibility).

[sigal-tests-fail.txt](https://github.com/saimn/sigal/files/2342898/sigal-tests-fail.txt)

**Comment by saimn** [comment]
Hum, I don't remember why this was needed... I'm testing on Travis to see if it can be removed (https://travis-ci.org/saimn/sigal/builds/423689271) otherwise I can xfail the test if the locale is not available.

**Comment by saimn** [comment]
I removed the locale change for now, it seems that we can live without.

**Comment by dvzrv** [comment]
Did this not make it to 1.4.1 somehow? I still have to exclude the tests.

**Comment by saimn** [comment]
@dvzrv - I released 1.4.1 just for the Click 7.0 compatibility issue. All the other changes are on master, I can do a new release in a near future (it will be 2.0 as this version will drop support for Python 2).
