### ISSUE TITLE
TypeError: 'ProgressBar' object is not an iterator

### ISSUE THREAD

**Issue by Damoun** [saimn/sigal#342]
Hi,

The python module `click` have been updated on tuesday and since then, I cannot run a build.
To fix this issue, I needed to install the previous version (6.7) of the module click before installing sigal:

`pip install click==6.7`

Could you freeze your requirements ?

**Comment by saimn** [comment]
Thanks for the report, I have opened https://github.com/pallets/click/issues/1125 to check if this is intended, or maybe something that can be fixed.

**Comment by saimn** [comment]
Fixed by https://github.com/saimn/sigal/commit/38f5c80f10845c9857e17a268ae2190ba517c548, and also available with version 1.4.1 (https://pypi.org/project/sigal/1.4.1/).

**Comment by alcoralcor** [comment]
Maybe it also should be interesting to fix dependencies versions in requirements.txt ? (ie click==6.7). It'll permit to always have a production version.

**Comment by saimn** [comment]
@alcoralcor - This kind of issue is rare enough, I prefer not to pin unless there is a good reason.
