### ISSUE TITLE
Photoswipe theme doesn't show image thumbnails when Javascript is disabled

### ISSUE THREAD

**Issue by aubade** [saimn/sigal#350]
Both the gallera and colorbox themes work admirably when the browser has Javascript disabled (With the mozilla NoScript plugin in my case). All thumbnails are shown and they load the full images when clicked. However, when the photoswipe theme is used, subfolders properly show thumbnails, but the actual images in each folder show up as blank white squares. The full images can still be viewed by clicking on the empty squares, though. 

Is it possible to fix this without impairing the with-Javascript functionality of the theme?

**Comment by saimn** [comment]
Not sure if it can be fixed easily, and this is probably more an issue for photoswipe, as it seems to have its own way to load thumbnails.

**Comment by saimn** [comment]
Closing as this is something that depends on Photoswipe.
