### ISSUE TITLE
Feeds plugin and Sigal in a subdirectory

### ISSUE THREAD

**Issue by jeekajoo** [saimn/sigal#361]
Hi,

1) It looks like "feeds" plugin doesn't handle having Sigal in a subdirectory.
In my case, Sigal is served in "pics/" and it's missing in all links of atom and rss feeds.

2) And also, both feeds produce links to `a-directory-in-sigal/#an-image.jpg` instead of `a-directory-in-sigal/an-image.jpg`. Thumbnails URL are fine, except they are missing 1).

Thanks
J.

**Comment by saimn** [comment]
Hi, thanks for reporting.
1. should be fixed by the commit above.
2. this link is valid for the galleria theme, it allows to show the image in the galleria viewer. But the other themes it was indeed wrong, it should be fixed as well.

**Comment by jeekajoo** [comment]
Hi, thank you
Sorry but that ain't workin'. Demo : https://jeekajoo.eu/files/pics/

```
rss_feed = {'feed_url': 'https://jeekajoo.eu/files/pics/feed.rss', 'nb_items': 100}
atom_feed = {'feed_url': 'https://jeekajoo.eu/files/pics/feed.atom', 'nb_items': 100}
```

**Comment by saimn** [comment]
@jeekajoo - Ah yes, sorry, and thanks for testing. It should be better now.

**Comment by jeekajoo** [comment]
It works (thumbnails appear correctly in the feed) but each feed item links to the folder in which it is stored :
* https://jeekajoo.eu/files/pics/feed.rss 
* https://jeekajoo.eu/files/pics/feed.atom

Thank you

**Comment by saimn** [comment]
Yeah, there is no mean currently to link directly to a given image.

**Comment by jeekajoo** [comment]
Ok if you say so, be it. Thanks
