### ISSUE TITLE
Album with pictures and sub-albums

### ISSUE THREAD

**Issue by oljask** [saimn/sigal#366]
I`ve got this warning:
Please move images to their own sub-album. Images in album pictures will not be visible.

Is there a way to make pictures in parent album visible, like in plain file manager?

**Comment by saimn** [comment]
Sorry, the possibility of mixing pictures and sub-albums was removed in v2.0. This was confusing and hopefully not a widely used feature, and this makes the templates simpler and easier to maintain.

**Comment by oljask** [comment]
I see.
If I understood correctly, I still can achieve this, if I make custom theme. Is this the right way?

**Comment by saimn** [comment]
Hmm yes, it is possible if you add the possibility to show pictures in the `album_list.html` template.

**Comment by t-animal** [comment]
I haven't rebuild my gallery in over a year now, because I really need this feature. Here is a simple way to recreate a theme based on the built-in colorbox theme. Only works on linux, obviously.

```
#!/bin/bash

set -e

SITE_PACKAGES=$(python -c 'import site; print(site.getsitepackages()[0])')

SOURCE_TEMPLATES="$SITE_PACKAGES"/sigal/themes/colorbox/templates
SOURCE_STATIC="$SITE_PACKAGES"/sigal/themes/colorbox/static

mkdir -p colorbox-enhanced/templates
ln -s $SOURCE_STATIC colorbox-enhanced/static
ln -s $SOURCE_TEMPLATES/* colorbox-enhanced/templates

cd colorbox-enhanced/templates

mv album_list.html album_list_base.html

PREAMBLE='''
{% extends "album_list_base.html" %}

{% block content %}

  <h2>Albums</h2>

  {{ super() }}

  {% if album.medias | length > 0 %}
  <h2>Images</h2>
  {% endif %}
'''

echo "$PREAMBLE" > album_list.html
tail -n+3 $SOURCE_TEMPLATES/album.html >> album_list.html
```

**Comment by t-animal** [comment]
@saimn While I was tinkering around I came up with some ideas that would allow easier extending of themes. They're based on the [jinja preset loader](https://github.com/saimn/sigal/blob/master/sigal/writer.py#L74) that you're already using but extending it for each template and hooks within the templates.

Pros:
- in user defined templates one could easily use`'{% extends !colorbox/album_list %)`
- Templates would become more extensible

Cons:
- the templates need to explicitly use the base from their template
- No solution for the static files referenced from the template

Before I had the fine-tuning done, I came up with the approach above, though. If you are open to the idea, I'll give it some more time and open a pull request. What do you think?

**Comment by saimn** [comment]
Yes seems interesting, making it easier to customize the templates would be great!
