### ISSUE TITLE
quiet mode for execution from cron

### ISSUE THREAD

**Issue by muelli** [saimn/sigal#376]
I want to run sigal regularly through a cron job.
Currently Sigal prints its status regardless, e.g.
```
Collecting albums, done.
  Sorting albums  [####################################]  100%
   Sorting media  [####################################]  100%
Collecting files  [####################################]  100%         
Processing files  [------------------------------------]  0/0
   Writing files  [####################################]  100%         

Done.
Processed 0 images (64 skipped) and 0 videos in 0.56 seconds.

```

To minimise the email I receive I would appreciate a quiet mode which only prints when the program faced a serious problem.

**Comment by saimn** [comment]
It seems a sensible idea, so I implemented this. I only left the "Done, processed ..." message since I think that it can be useful to have it in any case, but I could be convinced that it is better to print nothing. What do you think?

**Comment by muelli** [comment]
cool. thanks :)
My thinking is that if the command does not print anything then it is happy, "no news is good news".
And the less I will have to pipe things through grep to filter out strings to happier I will be.
Right now, cron generates an email when the process has printed something. If the process did not print anything, then cron does not send email. And I prefer it to not send email ;-)

**Comment by saimn** [comment]
Ok, let's go for the completely quiet version :)

**Comment by 153957** [comment]
@muelli hint: use something like [cronic](https://habilis.net/cronic/) to only send cron emails when the statuscode of the command is an error, then you do not need the command to be quiet, so that when things go wrong you get more output, for easier debugging..
