### ISSUE TITLE
name '__version__' is not defined when running py.test

### ISSUE THREAD

**Issue by simsong** [saimn/sigal#380]
This has an easy fix, but it requires providing a value of `__version__` when one is not available. I would like py.test to work, so I'll be sending you a pull request that addresses this problem.

```
slg@lastdance sigal % py.test
ImportError while loading conftest '/Users/slg/gits/sigal/tests/conftest.py'.
tests/conftest.py:7: in <module>
    from sigal import signals
sigal/__init__.py:54: in <module>
    @click.version_option(version=__version__)
E   NameError: name '__version__' is not defined
%
```

**Comment by saimn** [comment]
That's because you didn't install the project, but this should not happen and is now fixed, thanks.

**Comment by simsong** [comment]
Thank you. I like to be able to develop code without having to install it.
