### ISSUE TITLE
THEME_DIR - what is it?

### ISSUE THREAD

**Issue by dzieciou** [saimn/sigal#382]
The documentation on http://sigal.saimon.org/en/latest/themes.html#variables says that

> Gallery pages are created from a Jinja2 template index.html that must be located in THEME_DIR/templates.

I've tried to search for THEME_DIR: https://github.com/saimn/sigal/search?q=THEME_DIR&unscoped_q=THEME_DIR, and haven't found whether it is a variable defined somewhere or what.

Can you elaborate what it is and how to use it?

**Comment by saimn** [comment]
This is not a real variable, it is just to mention that the HTML templates must be in the `templates` subdirectory of the theme directory. And this theme directory is either one of the themes bundled with sigal, or a theme specified with `sigal build --theme|-t`

**Comment by dzieciou** [comment]
Thank you. Clear now. Closing the issue.
