### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by StyXman** [saimn/sigal#386]
For some reason `PIL.ExifTags` is reading my `LensModel` as an `int`, so the `strip()` call fails [here](https://github.com/saimn/sigal/blob/master/sigal/image.py#L323):

```
INFO: Wrong type <class 'int'> for LensModel:1
Traceback (most recent call last):
[...]
  File "/home/mdione/src/projects/nikola-gallery/lib/python3.8/site-packages/sigal/image.py", line 293, in get_exif_tags
    simple[tag] = data[tag].strip()
AttributeError: 'int' object has no attribute 'strip'
```

(I added a log line to see the type, tag and value; and removed the rest of the stack trace)

**Comment by saimn** [comment]
Fixed, thanks for the report!
