### ISSUE TITLE
Photoswipe vertical image full size flattened

### ISSUE THREAD

**Issue by koolok** [saimn/sigal#400]
Hi,

I use sigal to render my phone album, it used to work well with the 2.0 version, but since I update to 2.1.1, the vertical picture are not well rendered in "full screen view":
![Screenshot_2020-08-18 Photos](https://user-images.githubusercontent.com/17029055/90540445-84025e80-e181-11ea-8c85-a26671c3ef98.jpg)
The thumbnail looks good.
The original image looks like that:
![IMG_20200817_162127](https://user-images.githubusercontent.com/17029055/90540586-b7dd8400-e181-11ea-9d34-a4d8b4450011.jpg)

**Comment by saimn** [comment]
It works for me, with your image, on firefox and chromium. And Photoswipe has this nice zoom feature when the image is bigger than the screen... Which browser are your using ? Can you try again and make sure to reload the page ? Oh, and maybe you ran sigal with a build folder from the older version so it was not fully rebuild ?

**Comment by koolok** [comment]
> Which browser are your using ?

Firefox
> Can you try again and make sure to reload the page ?

I did Ctrl + F5
> Oh, and maybe you ran sigal with a build folder from the older version so it was not fully rebuild ?
I try to delete the previous folder and re-ran sigal, same issue.

I forgot to mentioned my changes in sigal.conf.py:
```
theme = 'photoswipe'
use_orig = True
medias_sort_reverse = True
```

**Comment by saimn** [comment]
Ok, I did not use `use_orig = True` and I can now see the problem. But that's an issue with your image, maybe because it has been rotated but its orientation flag was not modified? Its size is 3840 x 2160 (landscape) which confuses photoswipe.

```
❯ jhead pictures/90540586-b7dd8400-e181-11ea-9d34-a4d8b4450011.jpg
File name    : pictures/90540586-b7dd8400-e181-11ea-9d34-a4d8b4450011.jpg
File size    : 2001269 bytes
File date    : 2020:08:18 18:36:25
Camera make  : Sony
Camera model : E5823
Date/Time    : 2020:08:17 16:21:27
Resolution   : 3840 x 2160
Orientation  : rotate 90
Flash used   : No
Focal length :  4.2mm
Exposure time: 0.0025 s  (1/395)
Aperture     : f/2.0
ISO equiv.   : 40
Exposure bias: -0.67
Whitebalance : Auto
GPS Latitude : ? ?
GPS Longitude: ? ?
JPEG Quality : 90
```

**Comment by koolok** [comment]
> But that's an issue with your image
I don't think so, the Orientation flag tel to the browser how much the image should be rotated when it is displayed and the Resolution flag give the resolution of the actual image so, before rotation. That's why github is able to well display the image.

By the way, I took the image with open camera and did no modification.

Attached, the same image without metadata: `jhead -purejpg IMG_20200817_162127.jpg 
![IMG_20200817_162127](https://user-images.githubusercontent.com/17029055/94364373-0fe4a000-00c9-11eb-8e4a-5926161d8b61.jpg)

Should I report the bug on the photoswipe repo ?
`

**Comment by saimn** [comment]
@koolok - Indeed, you're right. But the problem is that photoswipe seems unmaintained lately ... (see discussion in #398).
