### ISSUE TITLE
img_format creates files with wrong suffix

### ISSUE THREAD

**Issue by hjbaader** [saimn/sigal#407]
Hi,

I used to have only JPEG images in my archive, now I have some TIFF Images too. So I set img_format to JPEG. Indeed it creates JPEG files from the TIFF, but it keeps the suffix .tif or .tiff rather changing it to .jpg.

I use Sigal 2.1.1 (just upgraded).

Thanks,
Hans-Joachim

**Comment by saimn** [comment]
Right, this was implemented in #360, but indeed it changes only the format but not the extension.

**Comment by hjbaader** [comment]
In the meantime I have patched the code and made it work for me. I'll try to make a patch against the current version.

**Comment by saimn** [comment]
Would be great to have a PR fixing this, thanks :)
