### ISSUE TITLE
Sigal fails when generating thumbnails for videos

### ISSUE THREAD

**Issue by thomasdn** [saimn/sigal#409]
Hi,

Sigal fails build when generating thumbnails for videos.

This is the output from sigal

    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9449.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9449.jpg (JPEG)
    INFO - Processing xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9450.jpg
    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9450.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9450.jpg (JPEG)
    INFO - Processing xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9452.jpg
    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9452.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9452.jpg (JPEG)
    INFO - Processing xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9453.jpg
    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9453.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9453.jpg (JPEG)
    INFO - Processing xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9454.jpg
    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9454.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9454.jpg (JPEG)
    INFO - Processing xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9455.jpg
    WARNING - The 'autorotate_images' and 'copy_exif_data' settings are not compatible because Sigal can't save the modified Orientation tag.
    DEBUG - Processor: ResizeToFit
    DEBUG - Save resized image to xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9455.jpg (JPEG)
    DEBUG - Save thumnail image: xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9455.jpg (JPEG)
    DEBUG - Video size: 1920, 1080 -> 480, 360
    DEBUG - Processing video: ffmpeg -i xxxxxxx/photo/view_copy/2019/in/2019-05-14-xxxxxxx/img_9457.mov -y -crf 23 -vf scale=480:trunc(ow/a/2)*2 xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9457.mp4
    DEBUG - Create thumbnail for video: ffmpeg -i xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9457.mp4 -an -r 1 -ss 3 -vframes 1 -y xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9457.jpg.tmp.jpg
    Traceback (most recent call last):
      File "xxxxxxx/photo/sigal/venv/bin/sigal", line 10, in <module>
        sys.exit(main())
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/__init__.py", line 158, in build
        gal.build(force=force)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/gallery.py", line 708, in build
        res = process_file(media_item)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/gallery.py", line 768, in process_file
        ret = processor(*args[3:])
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/video.py", line 185, in process_video
        converter=settings['video_converter'])
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/video.py", line 144, in generate_thumbnail
        image.generate_thumbnail(tmpfile, outname, box, fit=fit, options=options)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/image.py", line 159, in generate_thumbnail
        img = _read_image(source)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/sigal/image.py", line 71, in _read_image
        im = PILImage.open(file_path)
      File "xxxxxxx/photo/sigal/venv/lib/python3.7/site-packages/PIL/Image.py", line 2891, in open
        fp = builtins.open(filename, "rb")
    FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9457.jpg.tmp.jpg'

**Comment by thomasdn** [comment]
I just tried checking the  .mov file in question to see if there is anything special about this particular file. I cannot see anything out of the ordinary. The video file plays just fine.

But of course something might be wrong with this file.  Even if this is the case I think Sigal's behavior (failing) can be improvied. It would be much better if Sigal simply reported the error (e.g. "WARNING: Could not create thumbnail for video file X", or something like that) and then continued building the gallery. 
As it is right now I am unable to build a gallery at all as long as there is one or more problematic files in a set of several hundreds of thousands of files.

**Comment by fidergo-stephane-gourichon** [comment]
Hi. sigal user here.

Log shows a ffmpeg command line.

Can you run the ffmpeg command separately? Its output may help figuring out what's happening.

 ffmpeg -i xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9457.mp4 -an -r 1 -ss 3 -vframes 1 -y xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9457.jpg.tmp.jpg

> Even if this is the case I think Sigal's behavior (failing) can be improvied. It would be much better if Sigal simply reported the error (e.g. "WARNING: Could not create thumbnail for video file X", or something like that) and then continued building the gallery.

Yes, makes sense.

**Comment by thomasdn** [comment]
Well, the thumbnails folder in question contains zero *.jpg.tmp.jpg files. It  contains only proper .jpg files. So the command fails with "No such file or directory"

**Comment by fidergo-stephane-gourichon** [comment]
> Well, the thumbnails folder in question contains zero *.jpg.tmp.jpg files. It contains only proper .jpg files. So the command fails with "No such file or directory"

`*.jpg.tmp.jpg` is supposed to be an output of ffmpeg. `No such file or directory` might be a nonexistent output directory, or nonexistent input MP4, perhaps due to wrong current directory.

You may have to manually adjust the current directory or the paths in the command line to reach the proper mp4 input file and target an existing directory.

**Comment by thomasdn** [comment]
Oh, right. 

Here is ffmpeg output:


    $ ffmpeg -i xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9457.mp4 -an -r 1 -ss 3 -vframes 1 -y xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9457.jpg.tmp.jpg                                                                                                                 [R0 J0 L:4.78 4.69 4.73 U:0+04:55 pts/8 2539H]
    ffmpeg version 4.1.6-1~deb10u1 Copyright (c) 2000-2020 the FFmpeg developers
      built with gcc 8 (Debian 8.3.0-6)
      configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
      libavutil      56. 22.100 / 56. 22.100
      libavcodec     58. 35.100 / 58. 35.100
      libavformat    58. 20.100 / 58. 20.100
      libavdevice    58.  5.100 / 58.  5.100
      libavfilter     7. 40.101 /  7. 40.101
      libavresample   4.  0.  0 /  4.  0.  0
      libswscale      5.  3.100 /  5.  3.100
      libswresample   3.  3.100 /  3.  3.100
      libpostproc    55.  3.100 / 55.  3.100
    Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/img_9457.mp4':
      Metadata:
        major_brand     : isom
        minor_version   : 512
        compatible_brands: isomiso2avc1mp41
        encoder         : Lavf58.20.100
      Duration: 00:00:01.93, start: 0.000000, bitrate: 467 kb/s
        Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x270, 381 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)
        Metadata:
          handler_name    : Core Media Video
        Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 76 kb/s (default)
        Metadata:
          handler_name    : Core Media Audio
    Stream mapping:
      Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
    Press [q] to stop, [?] for help
    [swscaler @ 0x55e8bc6bbdc0] deprecated pixel format used, make sure you did set range correctly
    Output #0, image2, to 'xxxxxxx/photo/sigal/_build/2019/in/2019-05-14-xxxxxxx/thumbnails/img_9457.jpg.tmp.jpg':
      Metadata:
        major_brand     : isom
        minor_version   : 512
        compatible_brands: isomiso2avc1mp41
        encoder         : Lavf58.20.100
        Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 480x270, q=2-31, 200 kb/s, 1 fps, 1 tbn, 1 tbc (default)
        Metadata:
          handler_name    : Core Media Video
          encoder         : Lavc58.35.100 mjpeg
        Side data:
          cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
    frame=    0 fps=0.0 q=0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
    video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
    Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

**Comment by thomasdn** [comment]
Additional info: Ran "file" against the video file: 

`ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]`

**Comment by fidergo-stephane-gourichon** [comment]
Thanks for the information. 

>   Duration: 00:00:01.93, start: 0.000000, bitrate: 467 kb/s

FFmpeg detects a duration of less than 2 seconds. 

But the argument `-ss 3` instructs ffmpeg to skip the first 3 seconds (in case of video with fade-from-black, I guess).

So, FFmpeg finds nothing to output and sigal gets upset.

An option could be: sigal could first try with `-ss 3` then, in case of failure, try again without.

@saimn what do you think?

**Comment by thomasdn** [comment]
> An option could be: sigal could first try with -ss 3 then, in case of failure, try again without.

I think this is a good solution.

I think a better one would be:

1. Try with -ss 3
2. If that fails, then try without -ss 3
3. if that fails also, then report the error to the STDERR and continue generating the gallery

I think #3 is key.

I think #3 should be applied more broadly: If ffmpeg fails for any reason in any operation it should continue.

**Comment by saimn** [comment]
> Try with -ss 3
If that fails, then try without -ss 3

Yes, makes sense. Thanks @fidergo-stephane-gourichon for helping with the investigation.
I think the delay was added because often the first frame of a video is dark so not the best for a thumbnail.

> Even if this is the case I think Sigal's behavior (failing) can be improvied. It would be much better if Sigal simply reported the error (e.g. "WARNING: Could not create thumbnail for video file X", or something like that) and then continued building the gallery.

That's already the case. In debug it should crash if any error happen, to help debugging, but otherwise (normal and verbose mode) it shouldn't crash.

**Comment by thomasdn** [comment]
> That's already the case. In debug mode it should crash if any error happen, to help debugging, but otherwise (normal and verbose mode) it shouldn't crash.

Ah! That makes sense. I had it in debug mode.
I think it is a really good idea with the 3 sec delay in order to prevent black thumbnails.
A better heuristic might be to check how long the video is and then divide that by 3 and then take the thumbnail a third way in. I know this is a bit more complex to implement than a static delay...

**Comment by thomasdn** [comment]
Looked a bit into the code generating the thumbnail by calling ffmpeg.
It seems that the error handling does not work correctly: It checks for res.returncode being non-zero and then raises an exception. However, in the case with "-ss 3" on a video of length < 3 seconds, ffmpeg does not exit with a non-zero return code.

So I think a check should be added to check if the tmpfile was created or not. If it wasn't then re-run ffmpeg without -ss.

I have a modified generate_thumbnail that does this below:
                                                                                                                                                               
    def generate_thumbnail(source, outname, box, delay, fit=True, options=None,                                                                                 
                           converter='ffmpeg'):                                                                                                                 
        """Create a thumbnail image for the video source, based on ffmpeg."""                                                                                   
                                                                                                                                                                
        logger = logging.getLogger(__name__)                                                                                                                    
        tmpfile = outname + ".tmp.jpg"                                                                                                                          
                                                                                                                                                                
        # dump an image of the video                                                                                                                            
        cmd = [converter, '-i', source, '-an', '-r', '1',                                                                                                       
               '-ss', delay, '-vframes', '1', '-y', tmpfile]                                                                                                    
        logger.debug('Create thumbnail for video: %s', ' '.join(cmd))                                                                                           
        check_subprocess(cmd, source, outname)                                                                                                                  
                                                                                                                                                                
        # Sometimes ffmpeg fails with returncode zero but without producing an output file                                                                      
        # Thus, we need to check if an output file was created. If not, assume ffmpeg failed                                                                    
        if not os.path.isfile(tmpfile):                                                                                                                         
            logger.debug('Thumbnail generation failed. Likely due to very short video length.')                                                                 
            cmd = [converter, '-i', source, '-an', '-r', '1', '-vframes', '1', '-y', tmpfile]                                                                   
            logger.debug('Retrying to create thumbnail for video without delay: %s', ' '.join(cmd))                                                             
            check_subprocess(cmd, source, outname)                                                                                                              
                                                                                                                                                                
        # use the generate_thumbnail function from sigal.image                                                                                                  
        image.generate_thumbnail(tmpfile, outname, box, fit=fit, options=options)                                                                               
        # remove the image                                                                                                                                      
        os.unlink(tmpfile)                                                                                                                                      
                                                                                                                                                                
                                                                 
I have tested this on my local machine and it seems to work.

Will you consider adding this fix?
