### ISSUE TITLE
Video metadata using non-UTF8 encoding causes crash

### ISSUE THREAD

**Issue by progman32** [saimn/sigal#423]
[test.zip](https://github.com/saimn/sigal/files/6018670/test.zip)
Sigal crashes if a video has non-UTF8 text metadata present. I attach a sample file, which has a non-UTF8 string in the `handler_name` MP4 metadata attribute. This causes a problem as Sigal runs `ffmpeg -i` on the video, then attempts to interpret the output as UTF8. Since `ffmpeg -i` also dumps out metadata, this fails.

This is the site of the crash: https://github.com/saimn/sigal/blob/b265929ed0299f22aa99877f0fa71c1bbacbf1a3/sigal/video.py#L66

I suspect telling Python to ignore invalid UTF8 sequences will be enough to fulfill the code's purpose:
```python
stderr = res.stderr.decode('utf8', 'ignore')
```

With the above change, my gallery builds fine. I'm unsure what broader behavior Sigal exhibits with non-UTF8 text, as none of the metadata I have ends up in the generated HTML.

**Comment by progman32** [comment]
Also, a heartfelt thanks for this software. I used it to build a stable archive of family memories, spanning nearly a full century. I care a lot about the long-term durability of this archive, and a static site that can be hosted anywhere (or just kept as files) and browsed on almost anything is just the thing for it!

**Comment by saimn** [comment]
Thanks ! :)
I commited the fix you suggested.
