### ISSUE TITLE
Link for every image within colorbox gallery

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#427]
I'd like to share a link to a specific image, when then permits the user to keep browsing in the gallery. I can give a user the URL to a specific image (JPEG) file, but they can't browse from there. (I think this is similar to #93.)

**Comment by reagle** [comment]
I'm moving to PhotoSwipe, so won't worry about this anymore.

**Comment by saimn** [comment]
It depends on the Javascript library, some allows this but other not.
