### ISSUE TITLE
map and fullscreen don't play nice together

### ISSUE THREAD

**Issue by miiichael** [saimn/sigal#430]
Hello, I'm currently considering sigal as a viable replacement for llgal.

Testing with (mostly) default settings, I notice:
- when switching to the map (having set show_map, of course), switching back to showing the images is more complicated than it needs to be because the map is covering the toggle buttons for the map (and fullscreen)! I did eventually learn about the keyboard shortcuts.
- the map breaks if you switch to the map, back to images, fullscreen, then back to the map again. On the bright side, the map and fullscreen buttons become visible again...
![image](https://user-images.githubusercontent.com/4179353/117534155-d8f14800-b022-11eb-8ef4-9cf85bb541de.png)

- why does the map default to being centred on London? That's a very long way away. Defaulting to the location of the first image with a location would save a bunch of panning and zooming.

**Comment by saimn** [comment]
See #450, the map is now integrated in all themes, in a separate block. Not released yet, please test!

**Comment by miiichael** [comment]
Yep, this is definitely improved (after I nuked my ~/.local/lib/python3.9/site-packages/ to make it actually use the newer version), though I think I would be better to be able to swap between map and images view, rather than having both the map and images as separate blocks on the page.

The addition of resized images to the map is great, but it does make me wish that the map view implemented more of the images view functionality. :sweat_smile: eg. image fills entire block, and keyboard navigation works like the images view, plus I guess Escape to go back to the map. This is all well outside the scope of this bug report though. :)

**Comment by saimn** [comment]
With the new version the map is independent from the photo gallery, which has the benefit of allowing to use it in any theme. The old version integrated in galleria was more difficult to maintain, and was only in galleria. So it's a tradeoff between better integration and more general use.
