### ISSUE TITLE
Allow non-image files in the gallery

### ISSUE THREAD

**Issue by dsschult** [saimn/sigal#432]
I have a need for adding files that aren't images or videos to a gallery, specifically for pdfs and other media assets that may not be preview-able in a browser.  I'm wondering what the best way to go about this would be (I'm willing to make the modifications myself).

One option would be to make a plugin to handle "arbitrary" file types, and add a signal to hook into the file processing loop in `Album.__init__()`.  This seems better than making a global class, as it should affect fewer people.

Thoughts @saimn?

**Comment by saimn** [comment]
A plugin with a new signal seems a good idea :+1:
