### ISSUE TITLE
How do I get the path to a file

### ISSUE THREAD

**Issue by DuendeInexistente** [saimn/sigal#439]
Not an issue, but I can't find info on this anywhere. Would be good if I could just tell sigal to print all {{ possible.variables }}.

How do I get the path to a file? IE. 2021/twit.png .

**Comment by saimn** [comment]
Which path do you want ? (filename, local path, url)
The `Media` objects are available in the templates, through their subclasses `Image` and `Video`, so any attribute is available:
http://sigal.saimon.org/en/latest/themes.html#sigal.gallery.Media (and same below for `Image` and `Video` which add some attributes).
