### ISSUE TITLE
Use YAML front-matter instead of markdown metadata extension

### ISSUE THREAD

**Issue by 3onyc** [saimn/sigal#44]
I'd suggest using a front-matter like system such as the one that Jekyll has that parses from YAML (http://jekyllrb.com/docs/frontmatter/) to make the metadata more flexible.

With YAML you get support for lists, dictionaries, and whatnot which would be very useful in templates compared to plain strings.

**Comment by saimn** [comment]
There is now a plugin system, we can still discuss this if someone wants to work on it.
