### ISSUE TITLE
[Bug?]: Setting the title in the config vs. index.md

### ISSUE THREAD

**Issue by ikarus23** [saimn/sigal#441]
Hi. Thanks for the great software.

I think I found a bug. When I set the title in the config via the `title` parameter, the title will change for the gallery body (head line) but not for the `<title>` tag in the HTML header. If I set the title in the `index.md` it will change correctly in both locations.

**Comment by saimn** [comment]
The page title is defined as `<title>{{ album.title }}</title>` so only the album title. Maybe it should be something like `<title>{{ album.title }} - {{ title }}</title>` ?

**Comment by ikarus23** [comment]
Right. I just thought setting the parameter `title` should have the same outcome regardless of the point where it is defined. I did not notice that there are two different titles. Thanks for the explanation.

Also, your suggestion to use both titles in the HTML title tag looks good to me.
