### ISSUE TITLE
Feature request: Option to specify image for album thumbnail

### ISSUE THREAD

**Issue by thomasdn** [saimn/sigal#442]
Sometimes Sigal selects a poor image to use as the album thumbnail.
It would be great if it was possible to optionally specify an image to use for a specific album.

One simple way of implementing this is the following:

Support that if an image called sigal-album-thumbnail.jpg exists in the folder, then this image will be used as thumbnail for this album - and this image will be excluded form the album items as this is merely a meta-image and not part of the actual album images.
If a file called sigal-album-thumbnail.jpg does not exist, then sigal will just use whatever logic currently in place to select an album thumbnail.

**Comment by saimn** [comment]
It's already possible with the markdown file : http://sigal.saimon.org/en/latest/album_information.html

**Comment by thomasdn** [comment]
> It's already possible with the markdown file : http://sigal.saimon.org/en/latest/album_information.html

Ah. I see. Thanks.
