### ISSUE TITLE
Spurious "warning: album foo contains sub-albums and images" warning when building

### ISSUE THREAD

**Issue by ToxicFrog** [saimn/sigal#459]
E.g. `WARNING: Album Jewelry contains sub-albums and images. Please move images to their own sub-album. Images in album Jewelry will not be visible.`

It's entirely possible for templates to support mixed-mode albums, though (the one I'm using does). I don't know if it's reasonable to detect when this is happening and suppress the warning. I'm mostly leaving this here in case other people have mixed-mode albums and are looking for a workaround; the `album_list.html` template can iterate both `album.albums` to generate HTML for the subalbums, and `album.medias` to generate a gallery for the album contents.

**Comment by saimn** [comment]
Only the galleria theme supports that currently. See #408 for the full discussion. It would be nice to have a way to detect if a theme supports this feature but currently it doesn't exist. Closing as we should keep the discussion in #408, thanks.
