### ISSUE TITLE
Support encrypting videos in the encrypt plugin

### ISSUE THREAD

**Issue by dbw9580** [saimn/sigal#472]
Videos were not supported by the encrypt plugin, as a critical API ([`ReadableStream.pipeThrough`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/pipeThrough)) for piping decrypted video data into a player was missing in Firefox. Now that [Firefox 102 supports the said API](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/102#apis), it should be no longer blocked to implement encryption and decryption for videos as well.

cc #444

**Comment by saimn** [comment]
Closing to centralize the info in #444
