### ISSUE TITLE
keep_orig is broken and has no effect?

### ISSUE THREAD

**Issue by shuhaowu** [saimn/sigal#475]
This is a part of series of bugs that I've discovered while making a somewhat complex gallery with sigal.

This issue pertains to the `keep_orig` setting. The example can be see [in this repo](https://github.com/shuhaowu/sigal-bug-report/tree/master/keep-orig-broken).

So with a gallery where i have `keep_orig = True`:

```
title = "Test Gallery"
source = "gallery"
theme = "photoswipe"

img_size = (3000, 2000)
keep_orig = True
```

After building, I see the originals` directory get created, but nothing in the folder:

```
$ ls -l _build/original
total 0
```

In the code, I can see that the [original folder is created](https://github.com/saimn/sigal/blob/c3c44fe/sigal/gallery.py#L472-L474), but I can't find code where the file is copied.

**Comment by saimn** [comment]
That's because the original file is copied only if the theme use it, which is not the case with the photoswipe theme ...

**Comment by shuhaowu** [comment]
I have my own theme and it also didn't seem to have created it.

**Comment by saimn** [comment]
It will be copied if you use `media.big`:
https://github.com/saimn/sigal/blob/5ee967bf9e43d93a37658c87b25b95c54538ff66/sigal/themes/colorbox/templates/album.html#L9

**Comment by shuhaowu** [comment]
Ah I misunderstood. Thanks for the clarification!
