### ISSUE TITLE
Copy htaccess files and other misc

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#48]
In my source directory (and subdirectories) I have htaccess files governing the serving of the files (e.g., password protected). It'd be nice if sigal could copy those over to the destination as well.

**Comment by anarcat** [comment]
so once you'll have copied files in place, you'll notice that your gallery will prompt for passwords in sections even if they are not protected by .htaccess files. in case that's a problem for you, you may want to read up on the solution i found out in https://github.com/saimn/sigal/issues/220#issuecomment-354521247.
