### ISSUE TITLE
Does sigal work on mkv h265 files?

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#481]
I have a h265 mkv file but sigal doesn't seem to see it.

**Comment by frankenstein91** [comment]
I would like to add my problem to this problem. My video is included as MP4 file, but unfortunately I have only sound.

```
ffprobe version n5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '20221116/Frank Handy/PXL_20221116_052007351.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 131072
    compatible_brands: isomiso2mp41
    creation_time   : 2022-11-16T05:27:21.000000Z
    location        : +35.4473+139.6544/
    location-eng    : +35.4473+139.6544/
    com.android.capture.fps: 30.000000
  Duration: 00:07:08.61, start: 0.000000, bitrate: 43021 kb/s
  Stream #0:0[0x1](eng): Data: none (mett / 0x7474656D), 44 kb/s (default)
    Metadata:
      creation_time   : 2022-11-16T05:27:21.000000Z
      handler_name    : MetaHandle
  Stream #0:1[0x2](eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      creation_time   : 2022-11-16T05:27:21.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 3840x2160, 42778 kb/s, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2022-11-16T05:27:21.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -90.00 degrees

```

**Comment by bcleonard** [comment]
Are you only seeing the problem on a mac with safari or firefox?   

I ran across a bug that one of the browsers had (i can't remember which one) that has to do with the implementation on the mac.    Its not sigal's fault, but the default options result in no sound when played on a mac.   Works fine on windows, but its broken on a mac.   Only discovered it when my in-laws mentioned that they haven't been able to hear any videos in a year.

After a bunch of trial an error, I set the following option in sigal.conf.py:

`
mp4_options = ['-crf', '23', '-preset', 'faster', '-movflags', '+faststart', '-pix_fmt', 'yuv420p', '-b:a', '128k' ]
`
Its not fast, but i can finally get audio on a mac.

I've used this successfully when my video from both an iphone & sony handycam.

**Comment by frankenstein91** [comment]
Sound is working fine... Video is the problem.

I use Firefox on windows and Linux.

**Comment by saimn** [comment]
@reagle - sorry for the late response... did you add `.mkv` to `video_extensions` ?  the extension is not recognized as a video one by default, probably should be added

@frankenstein91 - for the video conversion sigal just use ffmpeg with some configurable options. So it's probably a matter of finding the correct options for ffmpeg (and please share if you find the good options, thanks).

**Comment by reagle** [comment]
@saimn, yes, thank you, this did the trick:

`video_extensions = [".mov", ".avi", ".mp4", ".webm", ".ogv", ".3gp", ".mkv"]`

**Comment by saimn** [comment]
@frankenstein91 - indeed, then it maybe some kind of browser issue ? Did you try with different browsers ?

For the original issue, I added mkv to `video_extensions` so I will close this issue. @frankenstein91, please open a new one if you think something can be done on sigal's side for your issue, thanks.

**Comment by frankenstein91** [comment]
@saimn I tried firefox and chrome on Linux and Windows. same problem on all
My ffmpeg and GPU are h265-able
