### ISSUE TITLE
Encrypt plugin: Password field hidden behind pictures.

### ISSUE THREAD

**Issue by JulienPalard** [saimn/sigal#483]
Hi!

I tried, for the first time, the `encrypt` plugin with `'ask_password': True` and found an issue: the password field is hidden behind the pictures:

![Screenshot 2022-11-27 at 21-34-08 Photos partagées -](https://user-images.githubusercontent.com/239510/204158379-3737b61b-2576-43cd-8f58-52ebd387b3ac.png)

This is using the colorbox theme. In the galleria theme this is "worse" as the prompt is completly hidden behind the scene.

Once the password entered it works though ♥

**Comment by saimn** [comment]
Not sure how that was supposed to work, I added a `z-index` and it seems to work :)

**Comment by JulienPalard** [comment]
Thank you!
