### ISSUE TITLE
Using galleria theme causes empty whitespace in the base index page

### ISSUE THREAD

**Issue by salehmu** [saimn/sigal#484]
When using `theme = "galleria"`, an empty white space is included in the index page. The following image is an example: 
![image](https://user-images.githubusercontent.com/74098495/204180705-4caf0e3a-6b27-4852-8017-2d056bc5e3b8.png)

I also tried to use the test sample from [https://github.com/saimn/sigal/tree/main/tests/sample](here): 
![image](https://user-images.githubusercontent.com/74098495/204180510-94386a54-e91e-4f5c-8ff9-13148337e4f5.png)

**Comment by salehmu** [comment]
Downgrading to 2.0 solved it. I did it arbitrary, I didn't test 2.1.

**Comment by saimn** [comment]
Indeed, this was due to #438.
