### ISSUE TITLE
tests fail with pillow release 10.0.0

### ISSUE THREAD

**Issue by gene-git** [saimn/sigal#493]
Several tests fail with:
 AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

python : 3.11.3
pillow: 10.0.0
pilkit: 2.0
os: Arch 

If I change src/sigal/image.py at line 168 to replace ANTIALIAS:

     method = PILImage.LANCZOS

Then below errors go away and new errors happen from pilkit module (I think) - so looks like it needs to be updated as well.
However pilkit has had no releases in 7 years. There is a fork of pilkit which looks like it fixes at least the deprecation of ANTIALIAS bug.

fork:   https://github.com/axoplasm/pilkit

I will try find time to test the forked version and report back

Full Error list:

```
============================================= short test summary info =============================================
FAILED tests/test_encrypt.py::test_encrypt - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_gallery.py::test_gallery - assert None
FAILED tests/test_gallery.py::test_gallery_max_img_pixels - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_image.py::test_process_image - assert 1 == 0
FAILED tests/test_image.py::test_generate_image - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_image.py::test_generate_image_imgformat - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_image.py::test_resize_image_portrait - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_image.py::test_exif_copy - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
FAILED tests/test_image.py::test_exif_gps - AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
============================= 9 failed, 74 passed, 1 deselected, 1 warning in 34.82s ==============================

```

**Comment by gene-git** [comment]
With the change to  src/sigal/image.py and using pilkit git HEAD which has the fixes for pillow 10 as well, all tests now pass again.

**Comment by saimn** [comment]
Yes, the problem comes from pilkit, so I pinned the version of Pillow earlier today (https://github.com/saimn/sigal/commit/8e364692ee00216540688657c3696c271fcb5d87). The fork you mentioned is just a fork with one commit to fix the issue, but this does not solve the issue of having new release of pilkit.

**Comment by gene-git** [comment]
Right - all fine with pilkit from git - be good if they make a release of that version so distros will pick it up.

**Comment by saimn** [comment]
Yes the fix is easy, the problem is to find someone that can merge PRs in pillow's repository and make releases. 
Ref https://github.com/matthewwithanm/pilkit/issues/59

**Comment by thomasdn** [comment]
> Yes the fix is easy, the problem is to find someone that can merge PRs in pillow's repository and make releases. Ref [matthewwithanm/pilkit#59](https://github.com/matthewwithanm/pilkit/issues/59)

I believe this issue was recently fixed.

**Comment by gene-git** [comment]
Thanks for taking care of this!
Can you make a 'release' of 2.4 so downstream will pick it up.

**Comment by saimn** [comment]
@gene-git - it's already on pypi: https://pypi.org/project/sigal/2.4/

**Comment by gene-git** [comment]
Yep thanks!
