### ISSUE TITLE
boto should be removed from optional dependencies

### ISSUE THREAD

**Issue by dvzrv** [saimn/sigal#513]
Hi! :wave: 

I maintain this project as a package for Arch Linux. We're currently cleaning up and dropping packages not compatible with Python 3.12, en route to updating to this newer Python interpreter.

I noticed that the [boto](https://github.com/boto/boto) upstream is deprecated and as such it should be removed from this project (and or its use be replaced with something else, e.g. boto3).
We will remove boto from the official repositories and in turn I will remove boto from the optional dependencies of the package on Arch Linux as well.

Thanks for your work :bow:

**Comment by saimn** [comment]
Hi @dvzrv,
Thanks for the notice. Porting the plugin to boto3 didn't seem obvious and I have no way to test this so I removed the plugin for now. 
If someone is using it and willing to dedicate some time to update it, contributions are welcome :)

**Comment by duststorm** [comment]
I had a conversion to boto3 staged in my personal branch, always wanted to contribute it back but it never happened.
This could be a good chance to contribute.
It's on the duststorm/sigal fork
Just need a bit of time to make separate feature branches of my different changes, and port them to the latest version of upstream main
