### ISSUE TITLE
Inability to set theme.url forces me to use a trailing slash when linking to sigal gallery

### ISSUE THREAD

**Issue by stemid** [saimn/sigal#526]
The way Sigal works now I can't link to domain.tld/mygallery because then the static/ urls will not work. I have to add domain.tld/mygallery/ which is a minor inconvenience when dealing with people who are not very computer literate.

If I could just set theme.url to my own value like ./mygallery or /mygallery to prefix the static path with then this would not be a problem.

Maybe I'm missing something obvious, can I fix this?

**Comment by saimn** [comment]
It's the way URL works, not sigal. `domain.tld/mygallery` and `domain.tld/mygallery/` are two different URL. 
The trailing slash can probably be removed with some server configuration (e.g. url rewriting with apache).

**Comment by stemid** [comment]
Yes but the issue that it produces is easily avoided if I could set theme.url to a slash for example, so the path is not relative anymore. Then it would be more accessible to non-technical users if they could simply type in domain.tld/gallery instead of having to remember the trailing slash.
