### ISSUE TITLE
Thumbnail crop should be higher

### ISSUE THREAD

**Issue by reagle** [saimn/sigal#64]
I believe the cropping used to make thumbnails is centered within the image, but this cuts off a lot of heads. I think the crop should be moved up a bit within the image.

**Comment by anarcat** [comment]
i would suggest closing this issue: yes, `SmartResize` is hit and miss, but there isn't much that can be done about this in Sigal itself. this is a pilkit problem, and should be reported there.

**Comment by reagle** [comment]
`SmartResize` was one possible solution. I think it'd still make sense to adopt @hyperking's approach.

**Comment by saimn** [comment]
I realize now that an option was added in #263 to specify how thumbnails are cropped (the `thumb_fit` and `thumb_fit_centering` settings). This allows to crop from the top of the image, so I think the issue can be closed.

**Comment by saimn** [comment]
Oh, and just to clarify things, thumbnails are created directly with Pillow, so not using pilkit's processors:
https://github.com/saimn/sigal/blob/master/sigal/image.py#L139-L155

**Comment by reagle** [comment]
Ah, I had not noticed the `thumb_fit_centering`, thanks!
