### ISSUE TITLE
Feature Request: RSS Feeds for Galleries

### ISSUE THREAD

**Issue by misilot** [saimn/sigal#73]
Hi,

It would be really cool, if the galleries, and the whole site had an RSS feed(s).

Thanks!

**Comment by catlee** [comment]
Is this fixed now that the pull request has been merged in?

**Comment by saimn** [comment]
Hi @catlee ,
The pull request has not been merged yet. I don't remember exactly what was missing, I will try to take a look into it when I can.

**Comment by hubertbanas** [comment]
@saimn 
Any thoughts on this?

**Comment by saimn** [comment]
@hubertbanas I will merge the plugin soon, it is currently very simple but it can be improved later if someone wants to work on it.

**Comment by saimn** [comment]
Done !

**Comment by hubertbanas** [comment]
Awesome! Thanks!
